/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigurationsRouteImport } from './routes/configurations'
import { Route as RegressionRouteImport } from './routes/regression'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DatasetsIndexRouteImport } from './routes/datasets.index'
import { Route as DatasetsDatasetIdRouteImport } from './routes/datasets.$datasetId'
import { Route as EvaluationsNewRouteImport } from './routes/evaluations.new'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments.index'
import { Route as ExperimentsExperimentIdRouteImport } from './routes/experiments.$experimentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationsRoute = ConfigurationsRouteImport.update({
  id: '/configurations',
  path: '/configurations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegressionRoute = RegressionRouteImport.update({
  id: '/regression',
  path: '/regression',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsDatasetIdRoute = DatasetsDatasetIdRouteImport.update({
  id: '/datasets/$datasetId',
  path: '/datasets/$datasetId',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsNewRoute = EvaluationsNewRouteImport.update({
  id: '/evaluations/new',
  path: '/evaluations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/experiments/',
  path: '/experiments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsExperimentIdRoute = ExperimentsExperimentIdRouteImport.update({
  id: '/experiments/$experimentId',
  path: '/experiments/$experimentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configurations': typeof ConfigurationsRoute
  '/regression': typeof RegressionRoute
  '/settings': typeof SettingsRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/evaluations/new': typeof EvaluationsNewRoute
  '/experiments/$experimentId': typeof ExperimentsExperimentIdRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/experiments/': typeof ExperimentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configurations': typeof ConfigurationsRoute
  '/regression': typeof RegressionRoute
  '/settings': typeof SettingsRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/evaluations/new': typeof EvaluationsNewRoute
  '/experiments/$experimentId': typeof ExperimentsExperimentIdRoute
  '/datasets': typeof DatasetsIndexRoute
  '/experiments': typeof ExperimentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configurations': typeof ConfigurationsRoute
  '/regression': typeof RegressionRoute
  '/settings': typeof SettingsRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/evaluations/new': typeof EvaluationsNewRoute
  '/experiments/$experimentId': typeof ExperimentsExperimentIdRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/experiments/': typeof ExperimentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configurations'
    | '/regression'
    | '/settings'
    | '/datasets/$datasetId'
    | '/evaluations/new'
    | '/experiments/$experimentId'
    | '/datasets/'
    | '/experiments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configurations'
    | '/regression'
    | '/settings'
    | '/datasets/$datasetId'
    | '/evaluations/new'
    | '/experiments/$experimentId'
    | '/datasets'
    | '/experiments'
  id:
    | '__root__'
    | '/'
    | '/configurations'
    | '/regression'
    | '/settings'
    | '/datasets/$datasetId'
    | '/evaluations/new'
    | '/experiments/$experimentId'
    | '/datasets/'
    | '/experiments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigurationsRoute: typeof ConfigurationsRoute
  RegressionRoute: typeof RegressionRoute
  SettingsRoute: typeof SettingsRoute
  DatasetsDatasetIdRoute: typeof DatasetsDatasetIdRoute
  EvaluationsNewRoute: typeof EvaluationsNewRoute
  ExperimentsExperimentIdRoute: typeof ExperimentsExperimentIdRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurations': {
      id: '/configurations'
      path: '/configurations'
      fullPath: '/configurations'
      preLoaderRoute: typeof ConfigurationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regression': {
      id: '/regression'
      path: '/regression'
      fullPath: '/regression'
      preLoaderRoute: typeof RegressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$datasetId': {
      id: '/datasets/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof DatasetsDatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations/new': {
      id: '/evaluations/new'
      path: '/evaluations/new'
      fullPath: '/evaluations/new'
      preLoaderRoute: typeof EvaluationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/experiments'
      fullPath: '/experiments/'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/$experimentId': {
      id: '/experiments/$experimentId'
      path: '/experiments/$experimentId'
      fullPath: '/experiments/$experimentId'
      preLoaderRoute: typeof ExperimentsExperimentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigurationsRoute: ConfigurationsRoute,
  RegressionRoute: RegressionRoute,
  SettingsRoute: SettingsRoute,
  DatasetsDatasetIdRoute: DatasetsDatasetIdRoute,
  EvaluationsNewRoute: EvaluationsNewRoute,
  ExperimentsExperimentIdRoute: ExperimentsExperimentIdRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
